# -*- coding: utf-8 -*-
#
# This file is part of INSPIRE.
# Copyright (C) 2014-2018 CERN.
#
# INSPIRE is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# INSPIRE is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with INSPIRE. If not, see <http://www.gnu.org/licenses/>.
#
# In applying this license, CERN does not waive the privileges and immunities
# granted to it by virtue of its status as an Intergovernmental Organization
# or submit itself to any jurisdiction.

version: '2.1'

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes_from:
      - test-static
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://inspirehep:dbpass123@test-database:5432/inspirehep
      - CELERY_BROKER_URL=pyamqp://guest:guest@test-rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://test-redis:6379/1
      - CACHE_REDIS_URL=redis://test-redis:6379/0
      - SEARCH_ELASTIC_HOSTS=test-indexer
    depends_on:
      test-database:
        condition: service_healthy
      test-indexer:
        condition: service_healthy
      test-redis:
        condition: service_healthy

  test-redis:
    image: redis:3.2.3
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD"
        - "bash"
        - "-c"
        - "exec 3<> /dev/tcp/127.0.0.1/6379 && echo PING >&3 && head -1 <&3 | grep PONG"

  test-indexer:
    extends:
      file: services.yml
      service: indexer
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 10
      test:
        - "CMD-SHELL"
        - "curl http://localhost:9200/_cluster/health | grep '.status.:.\\(green\\|yellow\\)'"

  test-rabbitmq:
    image: rabbitmq
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD"
        - "rabbitmqctl"
        - "status"

  test-database:
    extends:
      file: services.yml
      service: database
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD-SHELL"
        - "pg_isready --dbname=inspirehep --host=localhost --username=inspirehep"

  test-static:
    extends:
      file: services.yml
      service: static
